apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: blog-scaledobject
  namespace: aws9c  # 배포 대상 네임스페이스
spec:
  scaleTargetRef:
    name: aws9-deploy-blog  # 대상이 되는 Deployment 이름
  minReplicaCount: 1         # 기본 최소 Pod 개수 (오전 9시 이전, 오후 6시 이후엔 1개 유지)
  maxReplicaCount: 10        # 최대 Pod 수는 CPU 조건에 따라 확장 가능
  pollingInterval: 30        # (선택) 트리거 체크 주기 (초), 기본값은 30초
  cooldownPeriod: 300        # (선택) 축소 판단 유예 시간 (초), 5분 동안 다시 판단 안 함
  triggers:
    # 1. 시간 기반 고정 스케일링
    - type: cron
      metadata:
        timezone: Asia/Seoul          # 한국 시간 기준
        start: "0 9 * * *"            # 매일 오전 9시 시작
        end:   "0 18 * * *"           # 매일 오후 6시 종료
        desiredReplicas: "3"          # 이 시간 동안에는 Pod 수를 3개로 유지

    # 2. CPU 사용률 기반 스케일링
    - type: cpu
      metadata:
        type: Utilization             # CPU 활용률 기준
        value: "60"                   # 평균 CPU 60% 초과 시 Pod 수를 늘림
